name: Build Site
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Run script
      run: |
        chmod +x ./portis.sh
        ./portis.sh

    - name: Commit and push changes
      run: |
        git config --local user.email "yand@quien.es.eu.org"
        git config --local user.name "Stand Your Gists"
        git add index.html
        git commit -m "Update index.html" || echo "Nothing to commit, skipping push"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
